run_name: "modified-fem-weighted-fusion-v2"
data_root: "../../data/cityscapes"
use_modified: true

# training
epochs: 60
warmup_epochs: 0
batch_size: 4
accumulation_steps: 2
crop_size: 512
lr: 0.0001
weight_decay: 0.01
num_workers: 4
fp16: true